config/routes.rb
Rails.application.routes.draw do
  resources :bands

end

app/models/band.rb
class Band < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
    respond_to do |format|
      format.js
    end
  end

  # GET /bands/new
  def new
    @band = Band.new
    respond_to do |format|
      format.js
    end
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.js
      else
        format.js
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.js
      else
        format.js
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_params
      params.require(:band).permit(:name, :fanlevel, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_band.html.erb
<div id="band_<%= band.id %>" class="item col-xs-12 col-sm-3 col-md-3 col-lg-2" style=" margin:0 auto; position:relative; float:left"> 
  <div class="thumbnail">          
    <div class="caption">     
      <h3 class="text-left"><%= band.name.truncate(27, separator: /\s/) %></h3>     
      <span class="small">          
        <% if band.fanlevel != "" %>
        <%  for i in 1..band.fanlevel %>
        <span class="glyphicon glyphicon-heart pull-left " aria-hidden="true"></span> 
        <%  end %>
        <% end%>        
      </span>
      <div class="clearfix"></div>    
      <p class="small text-right"><span class="small text-right">
        <%= link_to ' ', band, :remote => true, :class => 'showlink btn btn-default btn-sm  glyphicon glyphicon-search' %></span> 
        <span class="small text-right">
          <%= link_to ' ', edit_band_path(band), :remote => true, :class => '  btn btn-default  btn-sm glyphicon glyphicon-pencil' %></span> 
          <span class="small text-right">
            <%= link_to ' ', band, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'small btn  btn-default btn-sm glyphicon glyphicon-trash' %></span>
      </p>
    </div>
  </div>
</div>

app/views/bands/_form.html.erb
<div class="col-lg-12 pull-left" id="box">
  <%= form_for(@band, :remote => true) do |f| %>
  <% if @band.errors.any? %>
  <div id="error_explanation">
    <h2>campos requeridos!</h2> 
  </div>
  <% end %>
  <div class="col-lg-12 pull-right">  
    <div class="field">
      <button id="btncerrar" class="btn btn-warning pull-right" type="button" >x</button>
    </div><br>
  </div>
  <div class="field small">
    <span class="text-danger small pull-left">(*)</span> Quiero ir al concierto de: <br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="field small">
   <span class="text-danger small">(*)</span>Cuan Fan eres de 1 a 7<br>      
   <%= f.number_field :fanlevel, class:'form-control' %>
 </div>
 <div class="field small">
   <span class="text-danger small">(*)</span> Breve Comentario <br>
   <%= f.text_field :description, class:'form-control' %>
 </div>
 <div class="field small">
   <span class="text-danger small">(*)</span>Foto Banda (externa) <br>
   <%= f.text_field :image, class:'form-control' %>
 </div>
 <div class="actions">
  <%= f.submit 'agregar', :class => 'btn btn-success pull-right ' %>
  <span class="text-danger small">(*) campos requeridos</span>
</div>
<% end %>
</div>

app/views/bands/_show.html.erb
<div class="container">
  <div class="col-lg-12 pull-right">  
    <div class="field">
     <%= link_to 'x', bands_path, :class => "btn btn-sm btn-info pull-right" %>
   </div> 
 </div>
 <div class="jumbotron">
   <p class="text-center"> 
     <%= image_tag(@band.image, class:"img-thumbnail") %>
   </p>
   <h1> <%= @band.name %></h1>
   <p class="lead"> <%= @band.description %></p>
   <p class="text-center"> Grado de fanatísmo:</p>
   <p class="text-center">
    <span class="text-center">
      <%  for i in 1..@band.fanlevel %>
      <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> 
      <%  end %>
    </span>
  </p>
</div>

app/views/bands/create.js.erb
<% if @band.errors.count == 0 %>
  
  $('#box').remove(); 
  $('#new-band-link').show();
  $('#bands .row').append('<%= j render("band", :band => @band) %>'); 
  
<% else %>
  $('#box').remove();    
  $('#new-band-link').after('<%= j render("form") %>');
<% end %>

app/views/bands/destroy.js.erb
$('#band_<%= @band.id %>').remove();

app/views/bands/edit.html.erb
<h1>Editing band</h1>

<%= render 'form' %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/edit.js.erb
$('#new-band-link').hide().after('<%= j render("form") %>');
//boton cerrar 
$("#btncerrar").click(function(){
  $("#box").hide();
  $('#new-band-link').show(); 
}); 

app/views/bands/index.html.erb
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>

<div id="bands" class="container-fluid" >
  <div class="row">

    <% if @bands.blank? %>

      <h1 class="text-info text-center">Tu Wishlist está vacia! </h1>
       
    <% else %>

        <% @bands.each do |band| %>
          <%= render "band", :band => band %>
        <% end %>
    
    <% end %>  

  </div>
</div>
<div id="boxShow" ></div>

app/views/bands/new.html.erb
<h1>New band</h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>

app/views/bands/new.js.erb
 $('#new-band-link').hide().after('<%= j render("form") %>');

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @band.name %>
</p>

<p>
  <strong>Fanlevel:</strong>
  <%= @band.fanlevel %>
</p>

<p>
  <strong>Description:</strong>
  <%= @band.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @band.image %>
</p>

<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>

app/views/bands/show.js.erb
$('#boxShow').empty();
$('#boxShow').fadeIn("slow").append('<%= j render("show") %>');

app/views/bands/update.js.erb
<% if @band.errors.count == 0 %>

  $('#new-band-link').show();
  $('#box').remove();    
  $('#edit_band_<%= @band.id %>').remove();
  $('#band_<%= @band.id %>').replaceWith('<%= j render @band %>');
  var estilo = $( "#resultadoCss").text();   
  $('#band_<%= @band.id %>').attr("style", estilo);
  $('.item').each(function () {
    var hue = 'rgba(' + (Math.floor((256-45)*Math.random()) + 134) + ',' + (Math.floor((256-88)*Math.random()) + 57) + ',' + (Math.floor((256-56)*Math.random()) + 130) + ',1)';
    $(this).css("background-color", hue);
  });
<% else %>
  $('#box').remove();    
  $('#edit_task_<%= @band.id %>').remove();
  $('#new-band-link').after('<%= j render("form") %>');


<% end %>

app/views/layouts/_navbar.html.erb
<ul class="nav navbar-nav">
  <li class="active"> <%= link_to 'Add Band', new_band_path, :remote => true, :id => "new-band-link" %> 
  </li>
 </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wishlist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>

<%= yield %>

</body>
</html>